### ISSUE TITLE
simplehttpserver - Does it work?

### ISSUE THREAD

**Issue by akinnee** [tikonen/blog#2]
simplehttpserver I just get a loading spinner forever in my browser when trying to go to any http://localhost:8000/ url while this server is running.

**Comment by rattrayalex** [comment]
Not working for me either. =(
I'm getting these warnings in the console as well:

```
body-parser deprecated bodyParser: use individual json/urlencoded middlewares node_modules/simplehttpserver/node_modules/express/lib/router/layer.js:95:5
express deprecated req.host: Use req.hostname instead node_modules/simplehttpserver/node_modules/body-parser/index.js:100:29
body-parser deprecated undefined extended: provide extended option node_modules/simplehttpserver/node_modules/body-parser/index.js:105:29
```

**Comment by tikonen** [comment]
Fixed!

**Comment by saianusha22** [comment]
how can you fixed this problem

**Comment by tikonen** [comment]
Update `express `and remove references to `bodyparser` from your code.

**Comment by krishna1501** [comment]
var express=require('express');
var path=require('path');
var app=express();
var morgan=require('morgan');
var mongoose=require("mongoose");
var personal=require("./models/reg_personaldb");
var bodyParser=require("body-parser");
app.set()
app.use(morgan('dev'));
app.use('/assets',express.static('assets'));
app.use('/countryplugin',express.static('countryplugin'));
app.use(bodyParser.urlencoded());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:true}));
mongoose.connect('mongodb://localhost:27017/practicum',function(err){
	if(err){
		console.log("Not Successful"+err);
	}else{
		console.log("DB Successful");
	}
});
app.post('/personal',bodyParser,function(req,resp){
	 var personaldata=new personal({
	 fullName:req.body.fullname,
	 address:req.body.address,
	 country:req.body.country,
	 gender:req.body.gender,
	 dob:req.body.dob,
	branch:req.body.branch,
	email:req.body.email,
	phone:req.body.phonenumber
	 });
	 
	personaldata.save(function(err){
	 	if(err){
	 		console.log(personaldata);
	 		console.log("Username Already exists"+err);
	 	}else{
	 		console.log(personaldata);
	 		console.log("user created");
	 		resp.send("user created");
	 	}
	 });
});
app.get('/home',function(req,resp){
	resp.sendFile('Home.html',{root: path.join(__dirname,'')});
})
app.get('/loginuser',function(req,resp){
	resp.sendFile('Login.html',{root: path.join(__dirname,'')});
})
app.get('/loginphone',function(req,resp){
	resp.sendFile('loginwithphone.html',{root: path.join(__dirname,'')});
})
app.get('/register',function(req,resp){
	resp.sendFile('register.html',{root:path.join(__dirname,'')});
})
app.post('/registereducation',function(req,resp){
	resp.sendFile('registereducation.html',{root:path.join(__dirname,'')});
})
var server=app.listen(1337,function(){
	console.log("Listening at port 1337");
});
this is the code which we have written can you please  fix this problem.

**Comment by gferrer807** [comment]
If anyone encounters this problem, try adding ```.json()``` after using body-parser with express. For example if I require body-parser as "parser" I would write ```app.use(parser.json())```. I recommend this before removing it and updating express
