### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Elexy** [tikonen/blog#4]
I'm a member of the Node.js Foundation Security Working Group and we received a report of a vulnerability in with this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by tikonen** [comment]
This repo is a collection of lots of stuff, what specific module here has a security issue?

**Comment by Elexy** [comment]
The module is https://www.npmjs.com/package/simplehttpserver. If you like I could Invite you to the HackerOne issue, to help address the issue.

**Comment by tikonen** [comment]
This module is intended only for local testing and dev use but if you
believe the issue should still be addressed please send me invite.
Thanks

**Comment by tikonen** [comment]
Closing as fixed.
https://hackerone.com/bugs?report_id=357109

**Comment by Ogemdi** [comment]
good fix
