### ISSUE TITLE
WebAssembly served with incorrect MIME type

### ISSUE THREAD

**Issue by thomasfn** [tikonen/blog#6]
WebAssembly (.wasm) files served with incorrect MIME type, it would make sense for simplehttpserver to serve them with the correct MIME type out of the box as the server is intended for debugging purposes.

Steps to reproduce:

1. Acquire or create a web assembly file (".wasm" extension)
2. Run simplehttpserver in the folder containing the .wasm file
3. Make a http GET request for the wasm file

Observed: WebAssembly .wasm files are served with "application/octet-stream" MIME type
Expected: WebAssembly .wasm files are served with "application/wasm" MIME type

**Comment by tikonen** [comment]
Added the out of the box support for .wasm mime type in release 0.3.0.
This version also contains support for defining custom mime types.
